// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoCO5qFurvgsFTcw3fHVR4s3aiEbHeAQ4',
    appId: '1:968981748019:web:4ca5341a558d3ae6da4646',
    messagingSenderId: '968981748019',
    projectId: 'ngodeyuk-25988',
    authDomain: 'ngodeyuk-25988.firebaseapp.com',
    storageBucket: 'ngodeyuk-25988.firebasestorage.app',
    measurementId: 'G-L3WVGK6W12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCawo1VZJivO6IVho7V409fkTHV3ma_2HA',
    appId: '1:968981748019:android:2e26ad67f2ce7a2eda4646',
    messagingSenderId: '968981748019',
    projectId: 'ngodeyuk-25988',
    storageBucket: 'ngodeyuk-25988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp8ZFrRXJ9hptDexp9oStQoeJgLNvRNQ8',
    appId: '1:968981748019:ios:16fa2c889223e23cda4646',
    messagingSenderId: '968981748019',
    projectId: 'ngodeyuk-25988',
    storageBucket: 'ngodeyuk-25988.firebasestorage.app',
    iosBundleId: 'com.example.ngodeyuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp8ZFrRXJ9hptDexp9oStQoeJgLNvRNQ8',
    appId: '1:968981748019:ios:16fa2c889223e23cda4646',
    messagingSenderId: '968981748019',
    projectId: 'ngodeyuk-25988',
    storageBucket: 'ngodeyuk-25988.firebasestorage.app',
    iosBundleId: 'com.example.ngodeyuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoCO5qFurvgsFTcw3fHVR4s3aiEbHeAQ4',
    appId: '1:968981748019:web:ca6ad70c1dc0b75ada4646',
    messagingSenderId: '968981748019',
    projectId: 'ngodeyuk-25988',
    authDomain: 'ngodeyuk-25988.firebaseapp.com',
    storageBucket: 'ngodeyuk-25988.firebasestorage.app',
    measurementId: 'G-72TR8DSRDF',
  );
}
